# Generated by Django 4.1.7 on 2023-04-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnwingApp', '0003_rename_category_id_course_category_and_more'),
        ('myapp', '0004_addcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='user_id',
            new_name='u_id',
        ),
        migrations.AlterField(
            model_name='addcart',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnwingApp.subcourse'),
        ),
    ]
