# Generated by Django 4.2 on 2023-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnwingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_title',
        ),
        migrations.AddField(
            model_name='course',
            name='course_desc',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(default=0),
        ),
    ]
